#ifndef GLOBALCONSTANTS_H
#define GLOBALCONSTANTS_H


#define APP_VERSION "v0.1"
#define APP_BUILD_DATE "23rd June 2025"

const double MAX_ZOOMOUT_THRESHOLD = 4.0;
const double TEXT_VISIBLE_THRESHOLD = 300.0;  // Text visible below this

#define VISTAR_SRC_MISSION_PLANNER "MISSION_PLANNER"
#define VISTAR_SRC_MISSION_EXECUTOR  "MISSION_EXECUTOR"

enum eVISTAR_CLASS {
    VISTAR_CLASS_NONE,
    VISTAR_CLASS_DRONE,
    VISTAR_CLASS_DRONE_SWARM,
    VISTAR_CLASS_FIGHTER,
    VISTAR_CLASS_UAV,
    VISTAR_CLASS_RADAR,
    VISTAR_CLASS_LAUNCHER,
    VISTAR_CLASS_MISSILE,
    VISTAR_CLASS_ROUTE
};

#endif // GLOBALCONSTANTS_H
